# Site settings
title: Nejc Kejzar
email: kejzar.n@gmail.com
description: my personal website
baseurl: # the subpath of your site, e.g. /blog
url: "https://nejckejzar.github.io/" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_username: NejcKejzar
gitlab_url: 
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
